Marking: Don't implement Comparable
Markings aren't really comparable, because e.g. p0=1,p1=0 and p0=0,p1=1 cannot
be ordered. The implementation solved this problem by throwing a
NotArrangableException in this case.

This causes problems with java 8's HashMap implementation. This implementation
switches to a tree-based implementation if too many hash collisions occur. This
implementation makes use of compareTo, if it is available.

See the following exception for details:

uniol.apt.adt.exception.NotArrangableException: markings not arrangable: [ [fork2:0] [cleaning0:0] [eating2:0] [cleaning1:0] [eating1:0] [eating0:0] [cleaning2:0] [waiting0:0] [waiting2:1] [waiting1:0] [thinking1:1] [thinking0:1] [thinking2:0] [fork1:1] [fork0:1] ] vs [ [fork2:1] [cleaning0:0] [eating2:0] [cleaning1:0] [eating1:0] [eating0:0] [cleaning2:0] [waiting0:1] [waiting2:0] [waiting1:0] [thinking1:1] [thinking0:0] [thinking2:1] [fork1:1] [fork0:0] ].
    at uniol.apt.adt.pn.Marking.compareTo(Marking.java:464)
    at uniol.apt.adt.pn.Marking.compareTo(Marking.java:42)
    at java.util.HashMap.compareComparables(HashMap.java:371)
    at java.util.HashMap$TreeNode.treeify(HashMap.java:1920)
    at java.util.HashMap.treeifyBin(HashMap.java:771)
    at java.util.HashMap.putVal(HashMap.java:643)
    at java.util.HashMap.put(HashMap.java:611)
    at uniol.apt.analysis.coverability.CoverabilityGraph.addNode(CoverabilityGraph.java:164)
    at uniol.apt.analysis.coverability.CoverabilityGraph.addArc(CoverabilityGraph.java:145)
    at uniol.apt.analysis.coverability.CoverabilityGraph.getPostsetEdges(CoverabilityGraph.java:106)
    at uniol.apt.analysis.coverability.CoverabilityGraphNode.getPostsetEdges(CoverabilityGraphNode.java:120)
    at uniol.apt.analysis.coverability.CoverabilityGraph.visitNode(CoverabilityGraph.java:81)
    at uniol.apt.analysis.coverability.CoverabilityGraph.access$100(CoverabilityGraph.java:49)
    at uniol.apt.analysis.coverability.CoverabilityGraph$1$1.hasNext(CoverabilityGraph.java:200)
    at uniol.apt.analysis.coverability.CoverabilityGraph.toLTS(CoverabilityGraph.java:268)
    at uniol.apt.analysis.coverability.CoverabilityGraph.toCoverabilityLTS(CoverabilityGraph.java:252)
    at uniol.apt.analysis.coverability.CoverabilityTest.testQuadstatePhilNet(CoverabilityTest.java:141)

Fix this by just removing Comparable and compareTo() from Marking. Apparently
they are unused anyway.

Signed-off-by: Uli Schlachter <uli.schlachter@informatik.uni-oldenburg.de>